#redis连接
spring:
  redis:
    host:
    password:
    port: 6380

#mongodb:
mongodb:
  primary:
    host:
    port: 27017
    database: cyfdb
    uri: mongodb://localhost:27017/cyfdb
  second:
     host:
     port: 27017
     database: cyfdb_second
     uri: mongodb://localhost:27017/cyfdb_second
